# Site settings
title: 9con
email: sammybaba@gmail.com
description: Just another set of apps icon for OS X
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://9con.ml" # the base hostname & protocol for your site
twitter_username: sammycheung
github_username:  isammyc

# Build settings
markdown: kramdown
